spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 120 mins
    refreshTokenExpiration: 604800 # 7 days
  profiles:
    active: dev
  flyway:
    clean-on-validation-error: true
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
